# Grouped dependencies
Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Layout/IndentationWidth:
    Width: 4

Metrics/LineLength:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: true

# Ignore all
AllCops:
  Exclude:
    - lib
    - db/schema.rb
