# Ignore all
AllCops:
  Exclude:
    - '/lib'

# Grouped dependencies
Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Layout/IndentationWidth:
    Width: 4

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Metrics/LineLength:
    Enabled: false
