# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef0cb7c663453fdca35b4ae59bc8013b1ad3708ec713b7d79f5a801359c91111da24fa216a17c334768eeef6d08753653e0a93af6822c0504686b9df09d06a8

test:
  secret_key_base: cf53cb4ad644d11210ab6e991aa500f3546cd04a71f513e86f85a7e8c215b51550bd497f6e9895cf7b49d377150af7368d4471b82942f0c9212e73b26f27df1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
