inherit_from:
    - ../.rubocop.yml

Lint/AmbiguousRegexpLiteral:
    Enabled: false

Lint/Debugger:
    Enabled: false

Style/RegexpLiteral:
    Enabled: false

Metrics/ParameterLists:
    Enabled: false

Metrics/ClassLength:
    Enabled: false